In [6]:
import numpy as np
from Pyfhel import Pyfhel, PyCtxt

In [7]:
np.set_printoptions(threshold=np.inf)

In [8]:
en1 = Pyfhel(context_params={'scheme':'ckks', 'n':2**13, 'scale':2**30, 'qi_sizes':[30]*5})

In [9]:
en1.keyGen()

## Test Encrypt

In [10]:
sample = np.random.rand(10, 10)
sample

array([[0.41679947, 0.17292579, 0.38720152, 0.85234545, 0.78295508,
        0.54879874, 0.57191423, 0.92302253, 0.36410033, 0.33699451],
       [0.74667658, 0.1487105 , 0.42414972, 0.88603528, 0.5382819 ,
        0.43294489, 0.91512011, 0.78719598, 0.81116449, 0.40871404],
       [0.79524214, 0.79533813, 0.45262055, 0.46375371, 0.89246687,
        0.93972513, 0.34729708, 0.21156867, 0.25684661, 0.72889173],
       [0.71112626, 0.72465562, 0.54957826, 0.72965617, 0.13080147,
        0.78069382, 0.69023219, 0.89943345, 0.40967142, 0.87765748],
       [0.93504808, 0.33186776, 0.68546092, 0.25129528, 0.72366509,
        0.07241303, 0.63828919, 0.30779838, 0.1151524 , 0.91867355],
       [0.53259298, 0.02031207, 0.6236964 , 0.84209192, 0.28415334,
        0.43377936, 0.34296907, 0.43484528, 0.63238364, 0.9972649 ],
       [0.16506785, 0.01513094, 0.8724767 , 0.56769231, 0.09618291,
        0.49062774, 0.27101175, 0.06682046, 0.4219108 , 0.14493663],
       [0.6140333 , 0.71514775, 0.4373869

In [11]:
en1.batchEnabled()

True

In [12]:
empty = np.zeros((10, 10), dtype=PyCtxt)
for i in range(10):
    for j in range(10):
        empty[i][j] = en1.encrypt(sample[i][j])
empty, empty.shape

(array([[<Pyfhel Ciphertext at 0x1b40c923ec0, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x1b42e90ff10, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x1b42e8e1940, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x1b42e8e18f0, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x1b42e8e1990, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x1b42e8e19e0, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x1b42e8e1a30, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x1b42e8e1ad0, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x1b42e8e1b20, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x1b42e8e1bc0, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>],
        [<Pyfhel Ci

In [13]:
sample2 = np.random.rand(10, 10)
empty2 = np.zeros((10, 10), dtype=PyCtxt)

for i in range(10):
    empty2[i] = en1.encrypt(sample2[i])

empty2, empty2.shape

(array([[<Pyfhel Ciphertext at 0x1b40cd5bd80, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x1b40cd5bd80, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x1b40cd5bd80, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x1b40cd5bd80, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x1b40cd5bd80, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x1b40cd5bd80, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x1b40cd5bd80, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x1b40cd5bd80, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x1b40cd5bd80, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x1b40cd5bd80, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>],
        [<Pyfhel Ci

Both of them provide the same result, however when encrypt as a whole output not implement error

In [14]:
# sample3 = np.random.rand(10, 10)
# empty2 = en1.encrypt(sample3)

## Test Calculation

In [15]:
cal1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype=np.float32)
cal2 = np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1], dtype=np.float32)

res = cal1*cal2
res

array([10., 18., 24., 28., 30., 30., 28., 24., 18., 10.], dtype=float32)

In [16]:
ctxt1 = en1.encrypt(cal1)
ctxt2 = en1.encrypt(cal2)

In [17]:
en1.decrypt(ctxt1)

array([ 9.99999433e-01,  1.99999935e+00,  3.00000104e+00,  3.99999882e+00,
        5.00000020e+00,  6.00000004e+00,  6.99999930e+00,  7.99999973e+00,
        9.00000303e+00,  1.00000003e+01, -1.86521787e-06, -9.02158973e-07,
        6.50969215e-07, -4.44146689e-07, -6.91967454e-07,  6.66912927e-07,
        3.72869897e-07, -7.42711302e-07,  6.76082634e-07, -7.85886624e-07,
        2.80264634e-08, -1.01996857e-06, -1.55253060e-06,  1.27876287e-06,
       -9.62282414e-08, -8.67646495e-07, -6.22369652e-07,  1.24487120e-06,
       -7.02936828e-07,  3.87830057e-07,  9.02353422e-07,  4.57452483e-07,
       -6.83679907e-07,  2.15764090e-07, -1.21303966e-08,  3.74779706e-07,
        2.11361337e-06, -1.13623326e-06, -2.55916000e-07,  2.85406051e-07,
       -3.97981238e-06, -5.45532386e-07, -1.15181037e-07,  2.01114638e-06,
        7.42437971e-08,  6.28015660e-08, -4.69925278e-07,  3.84317908e-07,
        1.42780086e-06, -3.78659181e-07, -2.49892847e-06, -8.56797839e-07,
        8.14648878e-07, -

In [18]:
en1.decrypt(ctxt2)

array([ 9.99999979e+00,  9.00000059e+00,  7.99999987e+00,  7.00000060e+00,
        5.99999914e+00,  5.00000035e+00,  4.00000394e+00,  3.00000038e+00,
        2.00000217e+00,  1.00000134e+00, -3.56735555e-07,  2.51424971e-07,
       -8.66801428e-08,  9.93852180e-07,  7.10682254e-07, -3.63205351e-07,
       -1.65456077e-08,  5.01765669e-07,  5.77687177e-07, -8.50430134e-07,
        5.96679173e-08, -3.39927300e-07,  1.71446334e-06, -2.24169511e-07,
        7.79688376e-07,  5.37812955e-07,  4.48055945e-09, -1.75215066e-06,
       -1.44747818e-06,  3.73624191e-07, -2.04065045e-07, -2.51706371e-08,
        1.14429666e-07, -2.00425713e-07, -2.50828738e-07, -2.25390298e-06,
       -2.68708313e-06, -9.87260285e-07,  6.59240838e-07, -5.78427846e-07,
        3.94699884e-06, -6.61868744e-07, -1.24273195e-07,  7.89546895e-07,
        4.25763094e-08, -3.37081680e-06, -1.94285402e-07, -5.29071336e-07,
       -6.01460955e-07, -6.89442402e-07, -1.05244714e-06,  1.07071934e-06,
       -7.79028763e-07,  

In [19]:
print(cal1*cal2)
print(en1.decrypt(ctxt1*ctxt2))
print()
print(cal1+cal2)
print(en1.decrypt(ctxt1+ctxt2))
print()
print(cal1-cal2)
print(en1.decrypt(ctxt1-ctxt2))

[10. 18. 24. 28. 30. 30. 28. 24. 18. 10.]
[ 9.99999412e+00  1.79999954e+01  2.40000080e+01  2.79999942e+01
  2.99999969e+01  3.00000023e+01  2.80000248e+01  2.40000023e+01
  1.80000256e+01  1.00000137e+01 -3.83781106e-13 -1.69392527e-13
 -1.89058308e-13 -4.66166830e-13 -5.07684338e-13  7.86453526e-14
 -4.31684548e-14 -5.56005397e-13  5.54576666e-13  1.99872566e-13
 -1.38961982e-12  4.92238961e-13 -2.97195123e-12 -6.49873501e-13
 -8.81299077e-14 -9.48730131e-14 -7.31723540e-14 -4.29921660e-12
  9.12455116e-13  3.25854048e-13 -1.08287024e-12  2.04939276e-13
 -1.19187311e-12 -3.00636780e-14 -3.42122369e-14 -9.49664367e-13
 -5.67076339e-12  9.45422970e-13 -1.96397521e-12 -1.49690175e-13
 -2.44042004e-11  4.36928774e-13 -4.91629026e-14  1.55837159e-12
  3.25681858e-13 -9.80824207e-14  7.74360206e-14  6.76605395e-13
 -1.76337667e-13  2.03141992e-13  3.90307398e-12 -1.50077584e-12
 -2.79078138e-13  1.25845154e-12  2.32054558e-12 -2.30659454e-12
 -9.29071964e-13  2.12010689e-12 -6.20971305e-13

In [20]:
en2 = Pyfhel()
en2.from_bytes_context(en1.to_bytes_context())
en2.from_bytes_public_key(en1.to_bytes_public_key())

366792

In [21]:
print(en1)
print(en2)

<ckks Pyfhel obj at 0x1b42e8e0080, [pk:Y, sk:Y, rtk:-, rlk:-, contx(n=8192, t=0, sec=128, qi=[30, 30, 30, 30, 30], scale=1073741824.0, )]>
<ckks Pyfhel obj at 0x1b42e90c620, [pk:Y, sk:-, rtk:-, rlk:-, contx(n=8192, t=0, sec=128, qi=[30, 30, 30, 30, 30], scale=1073741824.0, )]>


In [22]:
servernp = np.array([5, 6, 1, 4, 2, 6, 4, 2, 6, 7], dtype=np.int32)
mult = en2.multiply_plain(ctxt1, en2.encode(servernp), True)
mult


<Pyfhel Ciphertext at 0x1b42e90cd10, scheme=ckks, size=2/2, scale_bits=60, mod_level=1>

In [23]:
a = np.round(en1.decrypt(mult), 0)
a, a.shape

(array([ 5., 12.,  3., 16., 10., 36., 28., 16., 54., 70.,  0.,  0.,  0.,
         0.,  0., -0., -0.,  0.,  0., -0., -0., -0.,  0.,  0., -0., -0.,
         0.,  0., -0., -0., -0.,  0., -0., -0., -0.,  0., -0., -0., -0.,
         0.,  0., -0., -0.,  0.,  0.,  0., -0., -0.,  0.,  0., -0., -0.,
        -0.,  0.,  0.,  0.,  0., -0.,  0.,  0.,  0.,  0.,  0.,  0., -0.,
        -0.,  0., -0.,  0.,  0., -0.,  0., -0., -0., -0., -0.,  0., -0.,
         0., -0., -0.,  0.,  0.,  0., -0.,  0.,  0.,  0., -0., -0., -0.,
        -0.,  0.,  0., -0.,  0., -0., -0.,  0., -0.,  0.,  0., -0., -0.,
         0.,  0., -0.,  0.,  0., -0., -0., -0., -0., -0.,  0.,  0., -0.,
        -0.,  0.,  0.,  0., -0., -0., -0., -0.,  0., -0.,  0., -0.,  0.,
         0., -0.,  0., -0.,  0.,  0., -0., -0.,  0.,  0.,  0.,  0.,  0.,
        -0.,  0., -0., -0.,  0.,  0., -0.,  0.,  0.,  0.,  0., -0., -0.,
         0.,  0.,  0., -0., -0.,  0.,  0., -0., -0., -0.,  0.,  0., -0.,
         0., -0., -0.,  0.,  0., -0., -0.,  0.,  0.

In [24]:
cal1 * servernp

array([ 5., 12.,  3., 16., 10., 36., 28., 16., 54., 70.])

^^ Need to cut it down to correct amount

## Try 2D

In [46]:
simple2d = np.array([[1, 2], [3, 4]], dtype=np.float32)
simple2d

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [47]:
encrypt2d = np.zeros(simple2d.shape, dtype=PyCtxt)
for i in range(len(simple2d)):
    encrypt2d[i] = en1.encrypt(simple2d[i])
encrypt2d.shape

(2, 2)

In [27]:
server2d = np.array([[4, 3], [2, 1]], dtype=np.int32)
for i in range(len(encrypt2d)):
    for j in range(len(encrypt2d[i])):
        encrypt2d[i][j] = en2.multiply_plain(encrypt2d[i][j], en2.encode(server2d[i][j]), True)

In [28]:
simple2d * server2d

array([[4., 6.],
       [6., 4.]])

In [29]:
encrypt2d.shape

(2, 2)

In [30]:
decrypt2d = np.zeros(encrypt2d.shape, dtype=np.float32)
for i in range(len(encrypt2d)):
    for j in range(len(encrypt2d[i])):
        decrypt2d[i][j] = en1.decrypt(encrypt2d[i][j])[0]
decrypt2d


array([[4.       , 3.       ],
       [5.9999995, 2.9999998]], dtype=float32)

In [51]:
np.dot(simple2d, decrypt2d)

array([[ 7., 10.],
       [15., 22.]], dtype=float32)

In [49]:
a1 = np.dot(simple2d, encrypt2d)
a1

array([[<Pyfhel Ciphertext at 0x1b42e971b70, scheme=ckks, size=2/2, scale_bits=60, mod_level=1>,
        <Pyfhel Ciphertext at 0x1b42e971c60, scheme=ckks, size=2/2, scale_bits=60, mod_level=1>],
       [<Pyfhel Ciphertext at 0x1b42e971df0, scheme=ckks, size=2/2, scale_bits=60, mod_level=1>,
        <Pyfhel Ciphertext at 0x1b42e971da0, scheme=ckks, size=2/2, scale_bits=60, mod_level=1>]],
      dtype=object)

In [50]:
decrypt2d1 = np.zeros(a1.shape, dtype=np.float32)
for i in range(len(a1)):
    for j in range(len(a1[i])):
        decrypt2d1[i][j] = en1.decrypt(a1[i][j])[0]
decrypt2d1

array([[ 6.9999976,  6.9999976],
       [14.999996 , 14.999996 ]], dtype=float32)