In [284]:
import numpy as np
from Pyfhel import Pyfhel, PyCtxt

In [285]:
np.set_printoptions(threshold=np.inf)

In [337]:
en1 = Pyfhel(context_params={'scheme':'ckks', 'n':2**14, 'scale':2**30, 'qi_sizes':[30]*5})

In [338]:
en1.keyGen()

## Test Encrypt

In [288]:
sample = np.random.rand(10, 10)
sample

array([[0.95147622, 0.49938568, 0.67355957, 0.96554765, 0.66633842,
        0.16862391, 0.47827995, 0.87316636, 0.90165469, 0.0865144 ],
       [0.99910494, 0.84482801, 0.51305244, 0.29119824, 0.26389868,
        0.75479883, 0.31957559, 0.42128007, 0.45723678, 0.53360692],
       [0.0080645 , 0.15638176, 0.92703424, 0.65576716, 0.60472446,
        0.60814077, 0.01498522, 0.4971414 , 0.81221883, 0.60487358],
       [0.96478021, 0.02438886, 0.73608455, 0.41752268, 0.47798209,
        0.26260431, 0.87415113, 0.25751895, 0.87451789, 0.13781596],
       [0.75607795, 0.93935973, 0.88131601, 0.64342022, 0.89952608,
        0.76850989, 0.30294344, 0.81885996, 0.28154244, 0.10704032],
       [0.21459568, 0.01020303, 0.46727066, 0.10375613, 0.83251136,
        0.23681833, 0.24720641, 0.75529812, 0.5511753 , 0.94194935],
       [0.20664052, 0.57967165, 0.96767231, 0.42278809, 0.02215182,
        0.25409087, 0.67810293, 0.60558664, 0.38606169, 0.82760593],
       [0.85127384, 0.78927691, 0.9828668

In [289]:
en1.batchEnabled()

True

In [290]:
empty = np.zeros((10, 10), dtype=PyCtxt)
for i in range(10):
    for j in range(10):
        empty[i][j] = en1.encrypt(sample[i][j])
empty, empty.shape

(array([[<Pyfhel Ciphertext at 0x281fe70c9a0, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x281836e7600, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x281836de930, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x281d9936e30, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x2818971d210, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x2818971d350, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x2818971d7b0, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x2818971f9c0, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x2818971f2e0, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x2818971ec50, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>],
        [<Pyfhel Ci

In [291]:
sample2 = np.random.rand(10, 10)
empty2 = np.zeros((10, 10), dtype=PyCtxt)

for i in range(10):
    empty2[i] = en1.encrypt(sample2[i])

empty2, empty2.shape

(array([[<Pyfhel Ciphertext at 0x2818971e700, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x2818971e700, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x2818971e700, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x2818971e700, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x2818971e700, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x2818971e700, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x2818971e700, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x2818971e700, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x2818971e700, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x2818971e700, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>],
        [<Pyfhel Ci

Both of them provide the same result, however when encrypt as a whole output not implement error

In [292]:
# sample3 = np.random.rand(10, 10)
# empty2 = en1.encrypt(sample3)

## Test Calculation

In [293]:
cal1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype=np.float32)
cal2 = np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1], dtype=np.float32)

res = cal1*cal2
res

array([10., 18., 24., 28., 30., 30., 28., 24., 18., 10.], dtype=float32)

In [294]:
ctxt1 = en1.encrypt(cal1)
ctxt2 = en1.encrypt(cal2)

In [295]:
en1.decrypt(ctxt1)

array([ 9.99993175e-01,  2.00000436e+00,  3.00000199e+00,  4.00000190e+00,
        5.00000041e+00,  6.00000008e+00,  7.00000160e+00,  7.99999843e+00,
        9.00000007e+00,  9.99999979e+00, -2.13193272e-06, -2.23145200e-06,
        3.39256460e-07,  6.89738231e-07, -4.93223399e-06,  2.35941519e-06,
       -4.21318637e-07, -5.82184380e-08,  7.08827167e-06, -1.74040277e-06,
       -5.45013567e-07, -3.96829573e-07, -4.92029971e-06,  5.31661206e-06,
       -3.42942186e-07, -3.79236675e-06,  3.57895863e-06, -1.59365079e-06,
       -2.99336334e-06, -1.54005621e-07, -1.02426295e-06,  1.37403855e-06,
       -3.93214745e-07,  3.06162395e-07, -3.69303219e-07, -8.87467883e-07,
        4.75006859e-06, -6.59178366e-07, -6.34953396e-07,  2.15753594e-06,
       -6.17313721e-06,  3.24274783e-06, -9.26301737e-07,  1.96553603e-06,
       -1.97940347e-06, -3.39152446e-07, -3.58959817e-06, -1.47031606e-06,
       -1.23847724e-06,  5.95124751e-07,  1.23181674e-07, -1.99062184e-06,
       -2.53298143e-06, -

In [296]:
en1.decrypt(ctxt2)

array([ 9.99999619e+00,  9.00000087e+00,  8.00000246e+00,  6.99999959e+00,
        5.99999923e+00,  4.99999970e+00,  3.99999868e+00,  2.99999925e+00,
        1.99999450e+00,  9.99999850e-01, -7.97812867e-06,  1.40724415e-06,
        1.21772613e-07, -1.90310513e-07, -3.60148922e-06,  1.15040215e-06,
        1.88989461e-06,  3.88028490e-07,  1.51116616e-06, -3.39654319e-07,
       -7.07778836e-08,  4.40287679e-06, -3.29707863e-07,  4.80740790e-07,
       -4.68049027e-07, -1.84943300e-06, -3.28390230e-06,  4.08318571e-07,
        3.02719209e-06, -1.26755604e-07,  3.77484999e-07,  1.23783932e-07,
       -1.36725324e-06,  5.03064047e-06, -8.32902223e-07, -2.32298957e-07,
       -3.11892446e-07, -3.47275077e-06,  5.66473329e-06, -4.88927656e-06,
        1.71342604e-06,  1.22450218e-06,  1.96294969e-06, -2.49135316e-06,
       -1.87658529e-06,  7.12013811e-07, -1.34149047e-06,  1.41303241e-08,
        5.51265136e-06, -2.40547070e-06, -1.14803975e-06, -2.85007535e-06,
        1.86418197e-07,  

In [297]:
print(cal1*cal2)
print(en1.decrypt(ctxt1*ctxt2))
print()
print(cal1+cal2)
print(en1.decrypt(ctxt1+ctxt2))
print()
print(cal1-cal2)
print(en1.decrypt(ctxt1-ctxt2))

[10. 18. 24. 28. 30. 30. 28. 24. 18. 10.]
[ 9.99992793e+00  1.80000410e+01  2.40000233e+01  2.80000116e+01
  2.99999986e+01  2.99999986e+01  2.79999972e+01  2.39999893e+01
  1.79999507e+01  9.99999829e+00  3.67917929e-11 -9.26711811e-12
  1.16562152e-13 -1.79793720e-13  1.83286445e-11  2.25811449e-12
 -1.07255778e-12  1.75048202e-12  6.94924571e-11  1.56698209e-12
 -4.77165027e-13 -1.48786794e-12  1.73223545e-12  1.86206865e-11
  6.00755889e-12  5.80711322e-13 -1.18858246e-11 -1.47043377e-12
 -4.36584427e-12 -6.41901112e-13 -4.90627404e-14  4.46807180e-14
  2.73270030e-12  1.23383365e-11 -7.32223798e-13  4.17181578e-13
  3.73002478e-12  9.29390482e-13 -3.80227839e-12 -9.64449740e-12
 -2.41261883e-11  3.80075592e-12 -2.57476079e-13 -1.81168809e-11
  4.31488615e-12 -3.42018701e-12 -1.25288713e-12  8.21516695e-12
 -2.24854270e-11 -4.28754193e-12  9.36219977e-13  1.72989823e-11
 -1.70092126e-12 -8.08752318e-13 -4.21562527e-13 -2.57666845e-12
 -3.28194032e-14 -3.01853990e-11 -1.46729680e-14

In [298]:
en2 = Pyfhel()
en2.from_bytes_context(en1.to_bytes_context())
en2.from_bytes_public_key(en1.to_bytes_public_key())

1557417

In [299]:
print(en1)
print(en2)

<ckks Pyfhel obj at 0x281836de970, [pk:Y, sk:Y, rtk:-, rlk:-, contx(n=16384, t=0, sec=128, qi=[60, 30, 30, 30, 30, 30, 30, 30, 60], scale=1073741824.0, )]>
<ckks Pyfhel obj at 0x2818971f3c0, [pk:Y, sk:-, rtk:-, rlk:-, contx(n=16384, t=0, sec=128, qi=[60, 30, 30, 30, 30, 30, 30, 30, 60], scale=1073741824.0, )]>


In [300]:
servernp = np.array([5, 6, 1, 4, 2, 6, 4, 2, 6, 7], dtype=np.int32)
mult = en2.multiply_plain(ctxt1, en2.encode(servernp), True)
mult


<Pyfhel Ciphertext at 0x2818971f4c0, scheme=ckks, size=2/2, scale_bits=60, mod_level=1>

In [301]:
a = np.round(en1.decrypt(mult), 0)
a, a.shape

(array([ 5., 12.,  3., 16., 10., 36., 28., 16., 54., 70.,  0., -0.,  0.,
         0., -0., -0., -0.,  0.,  0.,  0., -0.,  0., -0., -0., -0., -0.,
         0., -0.,  0., -0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -0.,
         0., -0., -0., -0.,  0.,  0., -0., -0.,  0., -0.,  0., -0.,  0.,
         0.,  0., -0., -0.,  0.,  0.,  0., -0., -0., -0., -0., -0., -0.,
        -0., -0.,  0.,  0.,  0.,  0., -0., -0.,  0.,  0., -0., -0.,  0.,
         0.,  0., -0.,  0.,  0., -0.,  0.,  0., -0., -0., -0.,  0., -0.,
        -0.,  0.,  0., -0.,  0., -0.,  0.,  0.,  0.,  0., -0., -0., -0.,
         0.,  0., -0., -0.,  0.,  0., -0.,  0., -0., -0., -0.,  0.,  0.,
        -0.,  0.,  0., -0.,  0.,  0.,  0., -0.,  0., -0.,  0., -0.,  0.,
         0.,  0., -0.,  0., -0.,  0.,  0.,  0., -0., -0.,  0., -0., -0.,
         0., -0., -0.,  0., -0., -0., -0., -0., -0., -0., -0.,  0.,  0.,
         0., -0., -0.,  0., -0.,  0., -0., -0.,  0., -0.,  0., -0., -0.,
        -0.,  0.,  0., -0.,  0.,  0.,  0.,  0., -0.

In [302]:
cal1 * servernp

array([ 5., 12.,  3., 16., 10., 36., 28., 16., 54., 70.])

^^ Need to cut it down to correct amount

## Try 2D

In [303]:
simple2d = np.array([[1, 2], [3, 4]], dtype=np.float32)
simple2d

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [304]:
encrypt2d = np.zeros(simple2d.shape, dtype=PyCtxt)
for i in range(len(simple2d)):
    encrypt2d[i] = en1.encrypt(simple2d[i])
encrypt2d.shape

(2, 2)

In [305]:
server2d = np.array([[4, 3], [2, 1]], dtype=np.int32)
for i in range(len(encrypt2d)):
    for j in range(len(encrypt2d[i])):
        encrypt2d[i][j] = en2.multiply_plain(encrypt2d[i][j], en2.encode(server2d[i][j]), True)

In [306]:
simple2d * server2d

array([[4., 6.],
       [6., 4.]])

In [307]:
encrypt2d.shape

(2, 2)

In [308]:
decrypt2d = np.zeros(encrypt2d.shape, dtype=np.float32)
for i in range(len(encrypt2d)):
    for j in range(len(encrypt2d[i])):
        decrypt2d[i][j] = en1.decrypt(encrypt2d[i][j])[0]
decrypt2d


array([[4.0000153, 3.0000114],
       [5.9999967, 2.9999983]], dtype=float32)

In [309]:
np.dot(simple2d, decrypt2d)

array([[16.000008,  9.000008],
       [36.00003 , 21.000027]], dtype=float32)

In [310]:
a1 = np.dot(simple2d, encrypt2d)
a1

array([[<Pyfhel Ciphertext at 0x281fe70e110, scheme=ckks, size=2/2, scale_bits=60, mod_level=2>,
        <Pyfhel Ciphertext at 0x28183763880, scheme=ckks, size=2/2, scale_bits=60, mod_level=2>],
       [<Pyfhel Ciphertext at 0x281837627f0, scheme=ckks, size=2/2, scale_bits=60, mod_level=2>,
        <Pyfhel Ciphertext at 0x28183762a70, scheme=ckks, size=2/2, scale_bits=60, mod_level=2>]],
      dtype=object)

In [311]:
decrypt2d1 = np.zeros(a1.shape, dtype=np.float32)
for i in range(len(a1)):
    for j in range(len(a1[i])):
        decrypt2d1[i][j] = en1.decrypt(a1[i][j])[0]
decrypt2d1

array([[16.001472,  9.000835],
       [36.003323, 21.001963]], dtype=float32)

In [312]:
np.exp(10)

22026.465794806718

In [313]:
np.matmul(simple2d, encrypt2d)

array([[<Pyfhel Ciphertext at 0x28183760400, scheme=ckks, size=2/2, scale_bits=60, mod_level=2>,
        <Pyfhel Ciphertext at 0x28183760810, scheme=ckks, size=2/2, scale_bits=60, mod_level=2>],
       [<Pyfhel Ciphertext at 0x28183763830, scheme=ckks, size=2/2, scale_bits=60, mod_level=2>,
        <Pyfhel Ciphertext at 0x281837604f0, scheme=ckks, size=2/2, scale_bits=60, mod_level=2>]],
      dtype=object)

In [314]:
s = np.sum(encrypt2d, axis=0)/encrypt2d.shape[0]
s

array([<Pyfhel Ciphertext at 0x28183763c40, scheme=ckks, size=2/2, scale_bits=60, mod_level=2>,
       <Pyfhel Ciphertext at 0x28183763bf0, scheme=ckks, size=2/2, scale_bits=60, mod_level=2>],
      dtype=object)

In [315]:
for i in s:
    print(en1.decrypt(i)[0])

5.000462111379897
3.000278426784787


#### Test on Taylor series expansion to reproduce exponential

In [316]:
np.math.factorial(0)

1

In [339]:
anum = en1.encrypt(1)

In [343]:
def exp(x, n=4):
    d = 1.0
    rt = 0.0
    for i in range(n):
        rt += d/np.math.factorial(i)
        d = x*d
    return rt

In [328]:
print("Sample exp 1: ", np.exp(1))
for i in range(1, 10):
    print("n =", i, ":", exp(1, i))

Sample exp 1:  2.718281828459045
n = 1 : 1.0
n = 2 : 2.0
n = 3 : 2.5
n = 4 : 2.6666666666666665
n = 5 : 2.708333333333333
n = 6 : 2.7166666666666663
n = 7 : 2.7180555555555554
n = 8 : 2.7182539682539684
n = 9 : 2.71827876984127


In [340]:
ennum = exp(anum, 4)
en1.decrypt(ennum)[0]


2.6718009162771166

In [350]:
def HEsoftmax(a):
    return exp(a)/np.sum(exp(a))

In [351]:
HEsoftmax(anum)

TypeError: <Pyfhel ERROR> divisor must be float, int, array|list or PyPtxt with bfv/ckks scheme (is <class 'Pyfhel.PyCtxt.PyCtxt'> instead)