In [33]:
import numpy as np
from Pyfhel import Pyfhel, PyCtxt

In [64]:
np.set_printoptions(threshold=np.inf)

In [34]:
en1 = Pyfhel(context_params={'scheme':'ckks', 'n':2**13, 'scale':2**30, 'qi_sizes':[30]*5})

In [35]:
en1.keyGen()

## Test Encrypt

In [36]:
sample = np.random.rand(10, 10)
sample

array([[0.79448914, 0.05564081, 0.96488634, 0.52329531, 0.34919549,
        0.94686453, 0.29486035, 0.68581655, 0.43705469, 0.06167872],
       [0.12802162, 0.40298769, 0.4934937 , 0.96139453, 0.8777898 ,
        0.18784728, 0.82174413, 0.46870427, 0.13857144, 0.76240268],
       [0.4233356 , 0.37806557, 0.80842276, 0.42865719, 0.18715968,
        0.63810195, 0.22533593, 0.37651433, 0.54583922, 0.22855908],
       [0.69963671, 0.71869877, 0.89766852, 0.23086259, 0.50232393,
        0.27441004, 0.58901825, 0.90260312, 0.95643279, 0.68729748],
       [0.66350726, 0.57954665, 0.68515552, 0.80104096, 0.28103459,
        0.03265371, 0.74186029, 0.86519428, 0.13422825, 0.58624164],
       [0.19460382, 0.07254323, 0.3310587 , 0.2271845 , 0.38240714,
        0.11608562, 0.20149039, 0.80745378, 0.64599169, 0.08096671],
       [0.85315895, 0.79309131, 0.75948648, 0.64283772, 0.15998589,
        0.58369429, 0.10882379, 0.52616177, 0.96004463, 0.55869131],
       [0.63047999, 0.7631271 , 0.8280566

In [37]:
en1.batchEnabled()

True

In [38]:
empty = np.zeros((10, 10), dtype=PyCtxt)
for i in range(10):
    for j in range(10):
        empty[i][j] = en1.encrypt(sample[i][j])
empty, empty.shape

(array([[<Pyfhel Ciphertext at 0x1da7ff71670, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x1da7ff716c0, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x1da7ff41800, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x1da7ff71710, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x1da7ff713f0, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x1da7ff717b0, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x1da7ff71850, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x1da7ff718a0, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x1da7ff718f0, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x1da7ff71940, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>],
        [<Pyfhel Ci

In [39]:
sample2 = np.random.rand(10, 10)
empty2 = np.zeros((10, 10), dtype=PyCtxt)

for i in range(10):
    empty2[i] = en1.encrypt(sample2[i])

empty2, empty2.shape

(array([[<Pyfhel Ciphertext at 0x1da7f3ecdb0, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x1da7f3ecdb0, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x1da7f3ecdb0, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x1da7f3ecdb0, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x1da7f3ecdb0, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x1da7f3ecdb0, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x1da7f3ecdb0, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x1da7f3ecdb0, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x1da7f3ecdb0, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>,
         <Pyfhel Ciphertext at 0x1da7f3ecdb0, scheme=ckks, size=2/2, scale_bits=30, mod_level=0>],
        [<Pyfhel Ci

Both of them provide the same result, however when encrypt as a whole output not implement error

In [40]:
# sample3 = np.random.rand(10, 10)
# empty2 = en1.encrypt(sample3)

## Test Calculation

In [41]:
cal1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype=np.float32)
cal2 = np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1], dtype=np.float32)

res = cal1*cal2
res

array([10., 18., 24., 28., 30., 30., 28., 24., 18., 10.], dtype=float32)

In [42]:
ctxt1 = en1.encrypt(cal1)
ctxt2 = en1.encrypt(cal2)

In [68]:
en1.decrypt(ctxt1)

array([ 1.00000020e+00,  1.99999972e+00,  2.99999975e+00,  4.00000131e+00,
        4.99999658e+00,  5.99999599e+00,  7.00000000e+00,  8.00000234e+00,
        8.99999985e+00,  9.99999997e+00, -1.38461178e-09,  2.86247511e-06,
        5.51993203e-08,  2.87888924e-06, -3.55121867e-07,  1.18539110e-06,
       -5.97246957e-07, -2.39336276e-06,  7.05732376e-07, -1.60825260e-07,
       -2.70094261e-06, -2.84463447e-07,  3.49340918e-07, -5.59952144e-08,
        4.79101142e-07, -2.97090361e-08, -1.64761751e-07, -1.21541316e-06,
        2.23458120e-07, -7.55774445e-07, -6.16420170e-07, -2.52051282e-07,
        9.21978465e-08,  4.91204391e-07, -4.17008228e-07,  3.60675175e-08,
       -2.85895901e-07,  9.04810139e-07,  7.21421806e-07, -2.24534275e-06,
        6.08474128e-07,  4.49031772e-07, -1.35376561e-06, -1.17693654e-07,
        4.40952781e-07,  8.06381918e-07,  6.23096277e-07, -2.65454092e-06,
       -7.17385946e-07,  6.46603154e-08,  3.62522497e-06, -6.77435512e-08,
        1.94340041e-07, -

In [67]:
en1.decrypt(ctxt2)

array([ 1.00000007e+01,  8.99999992e+00,  7.99999988e+00,  6.99999904e+00,
        6.00000319e+00,  5.00000009e+00,  3.99999821e+00,  3.00000102e+00,
        1.99999964e+00,  9.99999716e-01,  7.45047279e-08,  1.57296561e-07,
       -1.55734860e-07, -4.55484026e-07, -1.96425759e-07, -5.92388876e-07,
       -2.57129997e-06, -2.07905651e-06,  2.06975136e-06, -3.49262711e-06,
        3.24505126e-07, -3.55583592e-07,  3.58998395e-07,  2.10603296e-07,
       -3.77541648e-07,  1.24252285e-08,  2.12647821e-07, -1.65850943e-07,
        3.15903903e-07, -1.87250017e-06, -2.17952179e-06,  9.55995316e-07,
       -2.77500918e-06, -1.15495628e-06,  1.63899424e-07,  1.66141982e-07,
       -5.69033040e-07, -1.45573102e-07, -1.49554772e-06,  1.44720438e-06,
        1.63020354e-06,  1.86286736e-07, -4.28307289e-07,  6.93865108e-08,
       -3.12182910e-08, -1.39424555e-06,  1.94772179e-07,  4.44153448e-07,
       -1.56029812e-06, -1.98677794e-07, -4.85252405e-07,  3.77986739e-07,
        3.35503026e-07, -

In [45]:
print(cal1*cal2)
print(en1.decrypt(ctxt1*ctxt2))
print()
print(cal1+cal2)
print(en1.decrypt(ctxt1+ctxt2))
print()
print(cal1-cal2)
print(en1.decrypt(ctxt1-ctxt2))

[10. 18. 24. 28. 30. 30. 28. 24. 18. 10.]
[ 1.00000027e+01  1.79999974e+01  2.39999976e+01 ...  4.30934665e-12
 -2.07487965e-12  2.58653887e-13]

[11. 11. 11. 11. 11. 11. 11. 11. 11. 11.]
[ 1.10000009e+01  1.09999996e+01  1.09999996e+01 ... -3.77371248e-06
  1.13858438e-06 -2.79175075e-06]

[-9. -7. -5. -3. -1.  1.  3.  5.  7.  9.]
[-9.00000052e+00 -7.00000019e+00 -5.00000013e+00 ... -5.80222896e-07
  6.70315048e-07 -1.77501942e-06]


In [46]:
en2 = Pyfhel()
en2.from_bytes_context(en1.to_bytes_context())
en2.from_bytes_public_key(en1.to_bytes_public_key())

366904

In [47]:
print(en1)
print(en2)

<ckks Pyfhel obj at 0x1da7ff70fd0, [pk:Y, sk:Y, rtk:-, rlk:-, contx(n=8192, t=0, sec=128, qi=[30, 30, 30, 30, 30], scale=1073741824.0, )]>
<ckks Pyfhel obj at 0x1da7ff7db60, [pk:Y, sk:-, rtk:-, rlk:-, contx(n=8192, t=0, sec=128, qi=[30, 30, 30, 30, 30], scale=1073741824.0, )]>


In [54]:
servernp = np.array([5, 6, 1, 4, 2, 6, 4, 2, 6, 7], dtype=np.int32)
mult = en2.multiply_plain(ctxt1, en2.encode(servernp), True)
mult


<Pyfhel Ciphertext at 0x1da7ff7f600, scheme=ckks, size=2/2, scale_bits=60, mod_level=1>

In [69]:
a = np.round(en1.decrypt(mult), 0)
a, a.shape

(array([ 5., 12.,  3., 16., 10., 36., 28., 16., 54., 70.,  0., -0.,  0.,
        -0.,  0., -0.,  0.,  0.,  0., -0.,  0., -0., -0., -0.,  0., -0.,
         0., -0.,  0.,  0.,  0., -0.,  0., -0., -0.,  0.,  0.,  0.,  0.,
        -0., -0.,  0., -0., -0.,  0.,  0.,  0.,  0., -0., -0.,  0.,  0.,
        -0.,  0., -0., -0.,  0.,  0.,  0.,  0.,  0., -0.,  0., -0.,  0.,
        -0., -0.,  0.,  0., -0.,  0., -0., -0.,  0., -0., -0.,  0.,  0.,
         0., -0., -0., -0., -0.,  0.,  0., -0., -0., -0., -0.,  0., -0.,
         0.,  0., -0., -0., -0., -0.,  0., -0., -0.,  0.,  0., -0.,  0.,
         0.,  0., -0.,  0., -0., -0., -0.,  0., -0., -0.,  0.,  0., -0.,
        -0.,  0.,  0., -0.,  0.,  0.,  0.,  0.,  0., -0., -0., -0., -0.,
        -0.,  0., -0., -0., -0.,  0., -0.,  0., -0.,  0., -0.,  0., -0.,
         0.,  0.,  0.,  0.,  0., -0., -0.,  0., -0., -0.,  0., -0.,  0.,
        -0.,  0.,  0.,  0., -0., -0.,  0., -0., -0., -0.,  0.,  0., -0.,
        -0., -0.,  0., -0.,  0.,  0., -0.,  0.,  0.

In [66]:
cal1 * servernp

array([ 5., 12.,  3., 16., 10., 36., 28., 16., 54., 70.])

^^ Need to cut it down to correct amount

## Try 2D

In [77]:
simple2d = np.array([[1, 2], [3, 4]], dtype=np.float32)
simple2d

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [80]:
encrypt2d = np.zeros(simple2d.shape, dtype=PyCtxt)
for i in range(len(simple2d)):
    encrypt2d[i] = en1.encrypt(simple2d[i])
encrypt2d.shape

(2, 2)

In [82]:
server2d = np.array([[4, 3], [2, 1]], dtype=np.int32)
for i in range(len(encrypt2d)):
    for j in range(len(encrypt2d[i])):
        encrypt2d[i][j] = en2.multiply_plain(encrypt2d[i][j], en2.encode(server2d[i][j]), True)

In [83]:
simple2d * server2d

array([[4., 6.],
       [6., 4.]])

In [87]:
encrypt2d.shape

(2, 2)

In [90]:
decrypt2d = np.zeros(encrypt2d.shape, dtype=np.float32)
for i in range(len(encrypt2d)):
    for j in range(len(encrypt2d[i])):
        decrypt2d[i][j] = en1.decrypt(encrypt2d[i][j])[0]
decrypt2d


array([[3.9999983, 2.9999988],
       [6.0000005, 3.0000002]], dtype=float32)